pyweb/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create,
         name='question_create'),
    path('answer/create/<int:question_id>/', views.answer_create,
         name='answer_create'),
]

pyweb/common/board/urls.py
from django.contrib.auth import views
from django.urls import path

app_name = 'common'

urlpatterns = [
    path('login/', views.LoginView.as_view(
            template_name='common/login.html'), name='login'),
]

pyweb/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index), #http://127.0.0.1:8000/
    path('board/', include('board.urls')), #http://127.0.0.1:8000/board
    path('common/', include('common.urls')), #http://127.0.0.1:8000/board
]

pyweb/templates/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create,
         name='question_create'),  #질문 등록
    path('answer/create/<int:question_id>/', views.answer_create,
         name='answer_create'),    #답변 등록
    path('question/delete/<int:question_id>/', views.question_delete,
         name='question_delete'),  #질문 삭제
]

pyweb/board/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)  #제목
    content = models.TextField()                #질문 내용
    create_date = models.DateTimeField()        #등록일
    create_date = models.DateTimeField()        #등록일
    modify_date = modles.DateTimeField(null=True, blank=True) #null 허용
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE) #외래키

    def __str__(self):
        return self.subject

# 답변 모델(테이블)
class Answer(models.Model):
    content = models.TextField()  #답변 내용
    create_date = models.DateTimeField()  #등록일
    question = models.ForeignKey(Question,
                on_delete=models.CASCADE) #외래키

    def __str__(self):
        return self.content

pyweb/common/board/models.py
from django.contrib.auth.models import User
from django.db import models

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) #글쓴이
    subject = models.CharField(max_length=200)  #제목
    content = models.TextField()                #질문 내용
    create_date = models.DateTimeField()        #등록일

    def __str__(self):
        return self.subject

# 답변 모델(테이블)
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) #글쓴이
    content = models.TextField()  #답변 내용
    create_date = models.DateTimeField()  #등록일
    question = models.ForeignKey(Question,
                on_delete=models.CASCADE) #외래키

    def __str__(self):
        return self.content

pyweb/templates/board/models.py
from django.contrib import admin

# Create your models here.

pyweb/board/forms.py
from django import forms
from board.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변 내용'
        }

pyweb/board/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone

from board.models import Question
from board.forms import QuestionForm, AnswerForm


def index(request):
    return render(request, 'board/index.html')
    # return HttpResponse("<h1>웹 메인 페이지 입니다.</h1>")

def question_list(request):
    question_list = Question.objects.all()
    context = {'question_list': question_list}
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'board/detail.html', context)

# 질문 등록
@login_required(login_url='common:login')
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST) #입력된 데이터가 있는 폼
        if form.is_valid(): # 폼이 유효성 검사를 통과했다면
            question = form.save(commit=False)  #가저장
            question.create_date = timezone.now()  # 등록일 생성
            form.save() #실제 저장
            return redirect('board:question_list') # 질문 목록 페이지 이동
    else: #get 방식
        form = QuestionForm()    #폼 객체 생성(빈 폼 생성)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)

# 답변 등록
@login_required(login_url='common:login')
def answer_create(request, question_id):
    # 질문이 1개 있어야 답변을 등록할 수 있음
    question = Question.objects.get(id=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False) #content만 저장
            answer.create_date = timezone.now() #답변 등록일
            answer.question = question  #외래키 생성
            form.save()
            return redirect('board:detail', question_id=question.id) #question.id 주의!!
    else:
        form = AnswerForm()   #빈 폼 생성
    context = {'question': question, 'form': form}
    return render(request, 'board/detail.html', context)

pyweb/common/board/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.models import Question
from board.forms import QuestionForm, AnswerForm


def index(request):
    return render(request, 'board/index.html')
    # return HttpResponse("<h1>웹 메인 페이지 입니다.</h1>")

def question_list(request):
    # question_list = Question.objects.all()
    question_list = Question.objects.order_by('-create_date') #내림 차순
    context = {'question_list': question_list}
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    # 모델에서 데이터가 있으면 가져오고 없으면 404 페이지 오류 처리를 함
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'board/detail.html', context)

# 질문 등록
@login_required(login_url='common:login') #로그인 페이지 이동
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST) #입력된 데이터가 있는 폼
        if form.is_valid(): # 폼이 유효성 검사를 통과했다면
            question = form.save(commit=False)  #가저장
            question.author = request.user  #세션 권한(로그인한) 있는 글쓴이
            question.create_date = timezone.now()  # 등록일 생성
            form.save() #실제 저장
            return redirect('board:question_list') # 질문 목록 페이지 이동
    else: #get 방식
        form = QuestionForm()    #폼 객체 생성(빈 폼 생성)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)

# 답변 등록
@login_required(login_url='common:login') #로그인 페이지 이동
def answer_create(request, question_id):
    # 질문이 1개 있어야 답변을 등록할 수 있음
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False) #content만 저장
            answer.author = request.user
            answer.create_date = timezone.now() #답변 등록일
            answer.question = question  #외래키 생성
            form.save()
            return redirect('board:detail', question_id=question.id) #question.id 주의!!
    else:
        form = AnswerForm()   #빈 폼 생성
    context = {'question': question, 'form': form}
    return render(request, 'board/detail.html', context)

# 질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('board:question_list')

pyweb/templates/board/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.models import Question
from board.forms import QuestionForm, AnswerForm


def index(request):
    return render(request, 'board/index.html')
    # return HttpResponse("<h1>웹 메인 페이지 입니다.</h1>")

def question_list(request):
    # question_list = Question.objects.all()
    question_list = Question.objects.order_by('-create_date') #내림 차순
    context = {'question_list': question_list}
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    # 모델에서 데이터가 있으면 가져오고 없으면 404 페이지 오류 처리를 함
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'board/detail.html', context)

# 질문 등록
@login_required(login_url='common:login') #로그인 페이지 이동
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST) #입력된 데이터가 있는 폼
        if form.is_valid(): # 폼이 유효성 검사를 통과했다면
            question = form.save(commit=False)  #가저장
            question.author = request.user  #세션 권한(로그인한) 있는 글쓴이
            question.create_date = timezone.now()  # 등록일 생성
            form.save() #실제 저장
            return redirect('board:question_list') # 질문 목록 페이지 이동
    else: #get 방식
        form = QuestionForm()    #폼 객체 생성(빈 폼 생성)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)

# 답변 등록
@login_required(login_url='common:login') #로그인 페이지 이동
def answer_create(request, question_id):
    # 질문이 1개 있어야 답변을 등록할 수 있음
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False) #content만 저장
            answer.author = request.user
            answer.create_date = timezone.now() #답변 등록일
            answer.question = question  #외래키 생성
            form.save()
            return redirect('board:detail', question_id=question.id) #question.id 주의!!
    else:
        form = AnswerForm()   #빈 폼 생성
    context = {'question': question, 'form': form}
    return render(request, 'board/detail.html', context)

# 질문 수정
@login_required(login_url='common:login')
def question_modify(request, questin_id):
    # 수정을 위해서 질문 1개 가져옴
    question = get_object_or_404(Question, pk=question_id)

    form = QuestionForm(instance=question)  #데이터가 이미 있는 폼
    context = {'form': form}
    return render(request, 'board/question_form.html', context)

# 질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request method == "POST":
            form = QuestionForm(request.POST, instance=question)
                form.is_valid():
                if form_is_valid():
                    question = form.save(commit=False)  #커밋 아직 안 됨
                    question.modify_date = timezone.now()   #수정일
                    question.author = request.user          #글쓴이
                    question.save()
                    return redirect('board:detail', question_id=question_id)
            else:
                form = QuestionForm(instance=question) #데이터가 이미 있는 폼
            context = {'form': form}
            return render(request, 'board/question_form.html', context)
             
    # 질문 삭제
@login_reuqired(login_url='common:login')
def question_delete(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    question.delete()

# 답변 삭제
@login_required(login_url='common:login)
def answer_delete(request, answer_id):
    # answer = Answer.objects.get(id=answer_id)
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()

pyweb/templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section id="detail">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <!-- 줄바꿈 : white-space: pre-line -->
            <div class="card-text" style="white-space: pre-line">
                {{ question.content }}
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
      <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
                {{ answer.content }}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 폼 -->
    <form action="{% url 'board:answer_create' question.id %}"
                    method="post" >
        {% csrf_token %}  <!-- 필수: 403 권한 에러 발생-->
        <!-- 유효성 검사 - 오류 처리 시작-->
            {% if form.errors  %}
                <div class="alert alert-danger">
                {% for field in form %}  <!-- 폼을 필드를 순회하면서 -->
                    {% if field.errors  %} <!-- 필드에 오류가 있으면 -->
                    <strong>{{ field.label }}</strong>
                        {{ field.errors }}  <!-- 에러 출력 -->
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
            <!-- 오류 처리 끝-->
        <div class="form-group">
            <textarea name="content" rows="10"
                      cols="50" class="form-control mb-3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">답변 등록</button>
    </form>
    </section>
</div>
{% endblock %}

pyweb/templates/board/index.html
<!DOCTYPE html>
<html lang="ko">
<!-- static 적용하려면 필수로 명시해야 함-->
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>main 페이지</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">
</head>
<body>
    <div id="container">
        <section id="main">
            <div class="poll">
                <a href="{% url 'poll:poll_list' %}">
                    <img src="{% static 'poll/images/vote.png' %}" alt="투표">
                    <p>설문 투표 바로가기</p>
                </a>
            </div>
            <div class="ocr">
                <a href="">
                    <img src="{% static 'poll/images/ocr.png' %}" alt="ocr">
                    <p>설문 투표 바로가기</p>
                </a>
            </div>
        </section>
    </div>
</body>
</html>

pyweb/templates/board/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section id="question_form">
        <h4 class="border-bottom pb-2">질문 등록</h4>
        <form action="" method="post">
            {% csrf_token %}
            <!--{{ form.as_p }}-->  <!-- input, textarea 태그 포함-->
            <!-- 유효성 검사 - 오류 처리 시작-->
            {% if form.errors  %}
                <div class="alert alert-danger">
                {% for field in form %}  <!-- 폼을 필드를 순회하면서 -->
                    {% if field.errors  %} <!-- 필드에 오류가 있으면 -->
                        {{ field.label }}
                        {{ field.errors }}  <!-- 에러 출력 -->
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
            <!-- 오류 처리 끝-->
            <div class="form-group">
                <label for="subject">제목</label>
                <input type="text" id="subject" name="subject"
                        class="form-control"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea name="content" id="content" rows="10"
                      class="form-control mb-3">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">등록</button>
        </form>
    </section>
</div>
{% endblock %}

pyweb/templates/board/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section id="question_list">
        <table class="table">
            <thead>
                <tr>
                    <th>번호</th><th>제목</th><th>작성일시</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list %}
                    {% for question in question_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td> <!-- 1부터 번호 시작 -->
                        <td>
                            <a href="{% url 'board:detail' question.id %}">
                                {{ question.subject }}
                            </a>
                        </td>
                        <td>{{ question.create_date }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>질문이 없습니다.</td>
                    </tr>
                {% endif %}
            </tbody>
         </table>
        <!-- 질문 등록 메뉴 -->
        <a href="{% url 'board:question_create' %}"
            class="btn btn-primary">질문 등록</a>
    </section>
</div>
{% endblock %}